# fly.toml app configuration file generated for ddddocr on 2023-12-22T14:20:24+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ddddocr"
primary_region = "nrt"
kill_timeout = "0s"

[experimental]
  auto_rollback = true

[build]
  builtin = "python"

[deploy]
  strategy = "rolling"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
